/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.avance_1.IGU;
import com.mycompany.avance_1.Cola; // Importa la clase Cola
import com.mycompany.avance_1.Dato;
/**
 *
 * @author josep
 */
public class SeleccionP extends javax.swing.JFrame {
 private final Cola colaRegular; // Variable para la cola regular
 private final Cola colaPreferencial; 
 private GllegadaP pGestionar;
 
    public SeleccionP(Cola cola, Cola colap) {
        initComponents(); 
        this.colaRegular = cola; // Guarda la referencia a la cola
        this.colaPreferencial = colap;
    }
// Método para establecer la referencia de pGestionar
    public void LlamarGestionar(GllegadaP pGestionarMain) {
        this.pGestionar = pGestionarMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Regular = new javax.swing.JButton();
        btn_Preferencial = new javax.swing.JButton();
        btn_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Regular.setText("Regular");
        btn_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegularActionPerformed(evt);
            }
        });

        btn_Preferencial.setText("Preferencial");
        btn_Preferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreferencialActionPerformed(evt);
            }
        });

        btn_Atras.setText("Atrás");
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btn_Regular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btn_Preferencial)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Atras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Regular)
                    .addComponent(btn_Preferencial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btn_Atras)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegularActionPerformed
        // TODO add your handling code here:
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre del paciente:");
        
        if (nombre != null && !nombre.trim().isEmpty()) {
        // Crea un nuevo objeto Dato con el nombre ingresado
        Dato nuevoPaciente = new Dato(nombre);
        
          // Llama al método enColar de la cola regular
        colaRegular.enColar(nuevoPaciente); // Asegúrate de que enColar acepte un objeto Dato
        
        // Muestra la cola actual en la consola o en un cuadro de diálogo
        String mostrarR = colaRegular.toString();
        System.out.println(mostrarR); // Puedes mostrar esto en un JOptionPane si prefieres
        javax.swing.JOptionPane.showMessageDialog(this, "Paciente agregado a la cola Regular: " + nombre);
    }else {
        // Maneja el caso en que no se ingresó un nombre
        javax.swing.JOptionPane.showMessageDialog(this, "Nombre no válido. Inténtalo de nuevo.");
    }
       
    }//GEN-LAST:event_btn_RegularActionPerformed

    private void btn_PreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreferencialActionPerformed
        // TODO add your handling code here:
 
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre del paciente:");
        
        if (nombre != null && !nombre.trim().isEmpty()) {
        // Crea un nuevo objeto Dato con el nombre ingresado
        Dato nuevoPaciente = new Dato(nombre);
        
          // Llama al método enColar de la cola preferencial
        colaPreferencial.enColar(nuevoPaciente); // Asegúrate de que enColar acepte un objeto Dato
        
        // Muestra la cola actual en la consola o en un cuadro de diálogo
        String mostrarp= colaPreferencial.toString();
        System.out.println(mostrarp); // Puedes mostrar esto en un JOptionPane si prefieres
        javax.swing.JOptionPane.showMessageDialog(this, "Paciente agregado a la cola Preferencial: " + nombre);
        
    }else {
        // Maneja el caso en que no se ingresó un nombre
        javax.swing.JOptionPane.showMessageDialog(this, "Nombre no válido. Inténtalo de nuevo.");
    }
    }//GEN-LAST:event_btn_PreferencialActionPerformed

    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pGestionar.setVisible(true);
    }//GEN-LAST:event_btn_AtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_Preferencial;
    private javax.swing.JButton btn_Regular;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
